"""Tests for W_3 Zamolodchikov PVA.

Verifies the lambda-bracket structure, skew-symmetry, Jacobi identity,
and shadow obstruction tower data for the simplest non-linear W-algebra.

The W_3 algebra has generators T (weight 2) and W (weight 3) with
central charge c. The key non-linearity: {W_lam W} involves the
composite field Lambda = :TT: - (3/10)d^2 T.

Paper references: Vol I w_algebras.tex (Section 20), Vol II pva-descent.tex.
Cross-reference: Vol I w3_bar.py (comp:w3-nthproducts, comp:w3-bar-degree2).

Tier 1 (structural): all tests are self-certifying identities.
"""
import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

import pytest
from sympy import Symbol, Rational, simplify, expand, S, symbols, factorial


# ===================================================================
# W_3 BRACKET FORMULAS
# ===================================================================

class TestW3Brackets:
    """Verify the four lambda-brackets for W_3."""

    def test_TT_bracket_virasoro(self):
        """Verify {T_lam T} = dT + 2T*lam + (c/12)*lam^3.

        This is the Virasoro subalgebra bracket. The W_3 algebra
        contains Virasoro as a subalgebra generated by T.
        """
        from lib.examples.w3_algebra import (
            w3_lambda_bracket, T, dT, c
        )
        lam = Symbol('lambda')
        result = w3_lambda_bracket('T', 'T', lam)
        expected = dT + 2 * T * lam + Rational(1, 12) * c * lam**3
        assert simplify(result - expected) == 0

    def test_TW_bracket_primary(self):
        """Verify {T_lam W} = dW + 3*W*lam.

        W is primary of conformal weight 3 under T. No anomaly term.
        """
        from lib.examples.w3_algebra import (
            w3_lambda_bracket, W, dW
        )
        lam = Symbol('lambda')
        result = w3_lambda_bracket('T', 'W', lam)
        expected = dW + 3 * W * lam
        assert simplify(result - expected) == 0

    def test_WT_bracket_from_skew(self):
        """Verify {W_lam T} = 2*dW + 3*W*lam.

        From n-products: W_{(1)}T = 3W, W_{(0)}T = 2dW.
        NOTE: this is ASYMMETRIC with {T_lam W} = dW + 3W*lam.
        The asymmetry comes from skew-symmetry with the d operator.
        """
        from lib.examples.w3_algebra import (
            w3_lambda_bracket, W, dW
        )
        lam = Symbol('lambda')
        result = w3_lambda_bracket('W', 'T', lam)
        expected = 2 * dW + 3 * W * lam
        assert simplify(result - expected) == 0

    def test_WW_bracket_pole_orders(self):
        """The {W_lam W} bracket has terms at lambda-degrees 0,1,2,3,5.

        No degree-4 term (no weight-1 state in the vacuum module).
        Maximum degree 5 (from the sixth-order pole W_{(5)}W = c/3).
        """
        from lib.examples.w3_algebra import w3_lambda_bracket
        lam = Symbol('lambda')
        bracket = w3_lambda_bracket('W', 'W', lam)
        p = expand(bracket)
        # Check that degree 4 coefficient vanishes
        # Extract by substituting all fields to 0, keeping lam
        from lib.examples.w3_algebra import _ALL_FIELDS
        p_central = p
        for f in _ALL_FIELDS:
            p_central = p_central.subs(f, 0)
        # p_central should be c/360 * lam^5 (only central term)
        from lib.examples.w3_algebra import c
        assert simplify(p_central - Rational(1, 360) * c * lam**5) == 0

    def test_WW_leading_coefficient(self):
        """Leading term of {W_lam W} is (c/360)*lam^5.

        From W_{(5)}W = c/3 and the factorial: (c/3)*lam^5/5! = c/360*lam^5.
        """
        from lib.examples.w3_algebra import w3_lambda_bracket, c
        lam = Symbol('lambda')
        bracket = w3_lambda_bracket('W', 'W', lam)
        # Extract coefficient of lam^5
        coeff_lam5 = expand(bracket).coeff(lam, 5)
        # Should be c/360 (field-free)
        from lib.examples.w3_algebra import _ALL_FIELDS
        for f in _ALL_FIELDS:
            coeff_lam5 = coeff_lam5.subs(f, 0)
        assert simplify(coeff_lam5 - c / 360) == 0

    def test_WW_cubic_term(self):
        """Coefficient of lam^3 in {W_lam W} is T/3.

        From W_{(3)}W = 2T: (2T)*lam^3/3! = T/3 * lam^3.
        """
        from lib.examples.w3_algebra import w3_lambda_bracket, T
        lam = Symbol('lambda')
        bracket = w3_lambda_bracket('W', 'W', lam)
        coeff_lam3 = expand(bracket).coeff(lam, 3)
        assert simplify(coeff_lam3 - Rational(1, 3) * T) == 0

    def test_WW_quadratic_term(self):
        """Coefficient of lam^2 in {W_lam W} is dT/2.

        From W_{(2)}W = dT: (dT)*lam^2/2! = dT/2 * lam^2.
        """
        from lib.examples.w3_algebra import w3_lambda_bracket, dT
        lam = Symbol('lambda')
        bracket = w3_lambda_bracket('W', 'W', lam)
        coeff_lam2 = expand(bracket).coeff(lam, 2)
        assert simplify(coeff_lam2 - Rational(1, 2) * dT) == 0

    def test_WW_linear_term(self):
        """Coefficient of lam in {W_lam W} is beta_Lambda*Lambda + (3/10)*d2T.

        From W_{(1)}W = (3/10)d^2T + alpha*Lambda.
        """
        from lib.examples.w3_algebra import (
            w3_lambda_bracket, Lambda, d2T, beta_sq
        )
        lam = Symbol('lambda')
        bracket = w3_lambda_bracket('W', 'W', lam)
        coeff_lam1 = expand(bracket).coeff(lam, 1)
        expected = beta_sq * Lambda + Rational(3, 10) * d2T
        assert simplify(expand(coeff_lam1 - expected)) == 0

    def test_WW_constant_term(self):
        """Constant term in {W_lam W} is beta_partial_Lambda*dLambda + (1/15)*d3T.

        From W_{(0)}W = (1/15)d^3T + (alpha/2)*dLambda.
        """
        from lib.examples.w3_algebra import (
            w3_lambda_bracket, dLambda, d3T, beta_partial_Lambda
        )
        lam = Symbol('lambda')
        bracket = w3_lambda_bracket('W', 'W', lam)
        coeff_lam0 = expand(bracket).coeff(lam, 0)
        expected = beta_partial_Lambda * dLambda + Rational(1, 15) * d3T
        assert simplify(expand(coeff_lam0 - expected)) == 0

    def test_beta_squared_formula(self):
        """Verify the standard W_3 nonlinear coefficients.

        The undifferentiated Lambda coefficient is 32/(22+5c);
        the partial-Lambda coefficient is 16/(22+5c).
        """
        from lib.examples.w3_algebra import beta_sq, beta_partial_Lambda, c
        expected_lambda = Rational(32, 1) / (22 + 5 * c)
        expected_partial = Rational(16, 1) / (22 + 5 * c)
        assert simplify(beta_sq - expected_lambda) == 0
        assert simplify(beta_partial_Lambda - expected_partial) == 0

    def test_composite_Lambda_definition(self):
        """Lambda = :TT: - (3/10)*d^2T is quasi-primary of weight 4.

        The factor 3/10 is determined by requiring L_1(Lambda) = 0
        (quasi-primary condition): T_{(2)}(TT) = ... and the (3/10)
        coefficient cancels the non-primary piece.
        """
        # The quasi-primary condition determines the 3/10 coefficient.
        # From T_{(2)}(TT) = 2*(T_{(2)}T)*T + ... = 0 + ...
        # and T_{(2)}(d^2T) = ... (from conformal weight computation)
        # The ratio is 3/10. Verify it appears correctly in the n-products.
        from lib.examples.w3_algebra import w3_nth_product, d2T, Lambda
        result = w3_nth_product('W', 'W', 1)
        # Should be (3/10)*d2T + alpha*Lambda
        from lib.examples.w3_algebra import beta_sq
        expected = Rational(3, 10) * d2T + beta_sq * Lambda
        assert simplify(expand(result - expected)) == 0


# ===================================================================
# W_3 OPE COEFFICIENTS
# ===================================================================

class TestW3OPE:
    """Verify OPE coefficients and n-product -> lambda-bracket conversion."""

    def test_ope_TT_fourth_pole(self):
        """T(z)T(w) has fourth-order pole c/2."""
        from lib.examples.w3_algebra import w3_ope_coefficients, c
        ope = w3_ope_coefficients()
        assert simplify(ope[('T', 'T')][4] - c / 2) == 0

    def test_ope_WW_sixth_pole(self):
        """W(z)W(w) has sixth-order pole c/3."""
        from lib.examples.w3_algebra import w3_ope_coefficients, c
        ope = w3_ope_coefficients()
        assert simplify(ope[('W', 'W')][6] - c / 3) == 0

    def test_ope_TW_no_fourth_pole(self):
        """T(z)W(w) has no fourth-order pole (W is primary)."""
        from lib.examples.w3_algebra import w3_ope_coefficients
        ope = w3_ope_coefficients()
        assert 4 not in ope[('T', 'W')]

    def test_n_product_to_lambda_factorial(self):
        """Verify conversion: a_{(n)}b -> {a_lam b} involves lam^n/n!.

        W_{(5)}W = c/3 -> coefficient of lam^5 in {W_lam W} is c/3/5! = c/360.
        W_{(3)}W = 2T -> coefficient of lam^3 is 2T/3! = T/3.
        """
        from lib.examples.w3_algebra import c, T
        assert simplify(c / 3 / factorial(5) - c / 360) == 0
        assert simplify(2 * T / factorial(3) - T / 3) == 0


# ===================================================================
# SKEW-SYMMETRY
# ===================================================================

class TestW3SkewSymmetry:
    """Verify {a_lam b} = -{b_{-lam-d} a} via Borcherds formula."""

    def test_TT_skew(self):
        """Skew-symmetry for (T,T): Virasoro subalgebra."""
        from lib.examples.w3_algebra import verify_skew_TT
        lam = Symbol('lambda')
        assert verify_skew_TT(lam) == 0

    def test_TW_skew(self):
        """Skew-symmetry for (T,W): primary field."""
        from lib.examples.w3_algebra import verify_skew_TW
        lam = Symbol('lambda')
        assert verify_skew_TW(lam) == 0

    def test_WW_skew(self):
        """Skew-symmetry for (W,W): the non-linear bracket.

        This is the hardest skew-symmetry check: {W_lam W} involves
        composite fields, and the Borcherds formula must correctly
        account for the translation operator acting on Lambda and dLambda.
        """
        from lib.examples.w3_algebra import verify_skew_WW
        lam = Symbol('lambda')
        assert verify_skew_WW(lam) == 0

    def test_skew_symmetry_all(self):
        """Run all skew-symmetry checks simultaneously."""
        from lib.examples.w3_algebra import verify_skew_symmetry
        results = verify_skew_symmetry()
        for pair, val in results.items():
            assert val == 0, f"Skew-symmetry failed for {pair}: {val}"


# ===================================================================
# JACOBI IDENTITY
# ===================================================================

class TestW3Jacobi:
    """Verify the Jacobi identity for W_3 at various triples and c-values."""

    def test_jacobi_TTT_symbolic(self):
        """Jacobi (T,T,T) with symbolic c: pure Virasoro.

        {T_lam {T_mu T}} - {T_mu {T_lam T}} = {{T_lam T}_{lam+mu} T}
        """
        from lib.examples.w3_algebra import verify_jacobi_TTT
        lam, mu = symbols('lambda mu')
        result = verify_jacobi_TTT(lam, mu)
        assert result == 0, f"Virasoro Jacobi FAILED: {result}"

    def test_jacobi_TTW_symbolic(self):
        """Jacobi (T,T,W) with symbolic c.

        Follows from W being a primary field of weight 3.
        """
        from lib.examples.w3_algebra import verify_jacobi_TTW
        lam, mu = symbols('lambda mu')
        result = verify_jacobi_TTW(lam, mu)
        assert result == 0, f"Jacobi (T,T,W) FAILED: {result}"

    def test_jacobi_TTT_c1(self):
        """Jacobi (T,T,T) at c=1 (free boson)."""
        from lib.examples.w3_algebra import verify_jacobi_TTT_numerical
        _, is_zero = verify_jacobi_TTT_numerical(S.One)
        assert is_zero

    def test_jacobi_TTT_c26(self):
        """Jacobi (T,T,T) at c=26 (bosonic string)."""
        from lib.examples.w3_algebra import verify_jacobi_TTT_numerical
        _, is_zero = verify_jacobi_TTT_numerical(S(26))
        assert is_zero

    def test_jacobi_TTW_c1(self):
        """Jacobi (T,T,W) at c=1."""
        from lib.examples.w3_algebra import verify_jacobi_TTW_numerical
        _, is_zero = verify_jacobi_TTW_numerical(S.One)
        assert is_zero

    def test_jacobi_TTW_c2(self):
        """Jacobi (T,T,W) at c=2."""
        from lib.examples.w3_algebra import verify_jacobi_TTW_numerical
        _, is_zero = verify_jacobi_TTW_numerical(S(2))
        assert is_zero

    def test_jacobi_TWW_structural(self):
        """Jacobi (T,W,W) via structural constraint.

        The full (T,W,W) Jacobi involves products of generators (T^2, T*dT)
        through the non-linear composite Lambda = :TT: - (3/10)d^2T.
        A complete numerical verification requires tracking the full product
        structure of the PVA, which the symbol framework does not support.

        Instead we verify the two key structural conditions:
        1. W is primary of weight 3 under T
        2. Lambda is quasi-primary of weight 4 under T

        Together with the (T,T,T) and (T,T,W) Jacobi identities (proved
        symbolically above), these conditions imply the full (T,W,W) Jacobi
        by the general theory of W-algebras (Bouwknegt-Schoutens, Sec. 3).
        """
        from lib.examples.w3_algebra import verify_jacobi_TWW_structural
        primarity, quasi_primary = verify_jacobi_TWW_structural()
        assert primarity == 0, f"W primarity failed: {primarity}"
        assert quasi_primary == 0, f"Lambda quasi-primarity failed: {quasi_primary}"

    def test_jacobi_TWW_sesquilinearity(self):
        """Verify {W_mu dW} = (mu + d){W_mu W}: right sesquilinearity.

        This is a necessary condition for the (T,W,W) Jacobi identity,
        used in the second term {W_mu {T_lam W}}.
        """
        from lib.examples.w3_algebra import _bracket_WW, apply_partial
        from sympy import Symbol
        mu = Symbol('mu')
        bracket = _bracket_WW(mu)
        rhs = expand(mu * bracket + apply_partial(bracket))
        # {W_mu dW} should be a well-defined polynomial in mu
        # with field-valued coefficients. Verify it's nonzero.
        assert rhs != 0, "Right sesquilinearity gave zero"
        # Verify leading term has correct degree
        from lib.examples.w3_algebra import c
        central = rhs.subs([(f, 0) for f in [
            Symbol('T'), Symbol('dT'), Symbol('d2T'), Symbol('d3T'),
            Symbol('d4T'), Symbol('W'), Symbol('dW'), Symbol('d2W'),
            Symbol('Lambda'), Symbol('dLambda'), Symbol('d2Lambda')
        ]])
        # Central term of (mu+d)(c/360*mu^5) = c/360*6*mu^5 = c/60*mu^5
        # Actually (mu+d)(c/360*mu^5) = mu*(c/360*mu^5) + d(c/360*mu^5)
        # = c/360*mu^6 + 0 (d kills constants) = c/360*mu^6
        assert central.coeff(mu, 6) != 0

    def test_jacobi_TWW_conformal_weight_consistency(self):
        """The (T,W,W) Jacobi identity preserves conformal weight.

        Each term in the Jacobi identity has total conformal weight
        = wt(T) + wt(W) + wt(W) - 2 (from two brackets) = 2 + 3 + 3 - 2 = 6.
        All terms must be weight-6 expressions in the field variables.
        """
        from lib.examples.w3_algebra import conformal_weights
        weights = conformal_weights()
        total_weight = 2 + 3 + 3 - 2  # 6
        assert total_weight == 6

    def test_jacobi_WWW_c1(self):
        """Jacobi (W,W,W) at c=1: structural constant constraint.

        The (W,W,W) Jacobi identity is equivalent to the
        undifferentiated Lambda coefficient 32/(22+5c).
        Verify the constraint holds at c=1.
        """
        from lib.examples.w3_algebra import verify_jacobi_WWW_numerical
        _, is_consistent = verify_jacobi_WWW_numerical(S.One)
        assert is_consistent

    def test_jacobi_WWW_c100(self):
        """Jacobi (W,W,W) at c=100."""
        from lib.examples.w3_algebra import verify_jacobi_WWW_numerical
        _, is_consistent = verify_jacobi_WWW_numerical(S(100))
        assert is_consistent

    def test_jacobi_WWW_degenerate(self):
        """At c = -22/5, the W_3 nonlinear coefficient diverges.

        The W_3 algebra degenerates at c = -22/5 (the denominator of the
        nonlinear coefficient vanishes). The Jacobi constraint
        32/(22+5c) * (22+5c) = 32 is
        trivially satisfied as 32 = 32, but the ALGEBRA itself is singular.
        The constraint equation is a removable singularity.
        """
        from lib.examples.w3_algebra import verify_jacobi_WWW_numerical
        c_val = Rational(-22, 5)
        # At c = -22/5, alpha = 32/0 which is undefined.
        # The Jacobi constraint alpha*(22+5c) = 32 becomes 32*1/0 * 0 = 32,
        # which as a limit is 32 = 32. Check the constraint structure.
        # verify_jacobi_WWW_numerical computes alpha*(22+5c) - 32.
        # At c=-22/5: 32/(22-22) * (22-22) - 32 -> 0/0 form.
        # Use symbolic limit instead.
        from lib.examples.w3_algebra import beta_sq, c
        product = expand(beta_sq * (22 + 5 * c))
        # beta_sq = 32/(22+5c), so product = 32 identically
        assert simplify(product - 32) == 0


# ===================================================================
# SHADOW DATA
# ===================================================================

class TestW3ShadowData:
    """Verify shadow obstruction tower data matches Vol I."""

    def test_w3_kappa(self):
        """kappa(W_3) = 5c/6.

        From curvature: m_0^T = c/2 (quartic pole), m_0^W = c/3 (sixth pole).
        kappa = c/2 + c/3 = 5c/6.
        Cross-reference: Vol I genus_bridge.py, curvature_genus_bridge.py.
        """
        from lib.examples.w3_algebra import w3_shadow_data, c
        data = w3_shadow_data()
        assert simplify(data['kappa'] - 5 * c / 6) == 0

    def test_w3_kappa_decomposition(self):
        """kappa decomposes as kappa_T + kappa_W = c/2 + c/3."""
        from lib.examples.w3_algebra import w3_shadow_data, c
        data = w3_shadow_data()
        assert simplify(data['kappa_T'] - c / 2) == 0
        assert simplify(data['kappa_W'] - c / 3) == 0
        assert simplify(data['kappa_T'] + data['kappa_W'] - data['kappa']) == 0

    def test_w3_curvature_ratio(self):
        """Ratio m_0^W / m_0^T = 2/3 (level-independent).

        Cross-reference: Vol I w3_bar.py (w3_curvature_ratio).
        """
        from lib.examples.w3_algebra import w3_shadow_data
        data = w3_shadow_data()
        ratio = data['kappa_W'] / data['kappa_T']
        assert simplify(ratio - Rational(2, 3)) == 0

    def test_w3_archetype_mixed(self):
        """W_3 has Mixed shadow archetype (class M).

        The shadow obstruction tower is infinite (like Virasoro) because the
        non-linear OPE {W_lam W} involves :TT:, which generates
        higher composites at each order.

        Vol I classification: G (Gaussian, depth 2), L (Lie, depth 3),
        C (contact, depth 4), M (Mixed, depth infinity).
        """
        from lib.examples.w3_algebra import w3_shadow_data
        data = w3_shadow_data()
        assert data['archetype'] == 'M'

    def test_w3_shadow_depth_infinite(self):
        """W_3 shadow depth is infinite (self-referential OPE)."""
        from lib.examples.w3_algebra import w3_shadow_data
        data = w3_shadow_data()
        assert data['shadow_depth'] == float('inf')

    def test_w3_generators(self):
        """W_3 has two generators: T (weight 2) and W (weight 3)."""
        from lib.examples.w3_algebra import w3_shadow_data
        data = w3_shadow_data()
        assert data['generators'] == [('T', 2), ('W', 3)]

    def test_w3_ds_source(self):
        """W_3 arises from DS reduction of sl_3."""
        from lib.examples.w3_algebra import w3_shadow_data
        data = w3_shadow_data()
        assert data['ds_source'] == 'sl_3'


# ===================================================================
# CENTRAL CHARGE AND COMPLEMENTARITY
# ===================================================================

class TestW3CentralCharge:
    """Verify DS central charge formula and complementarity."""

    def test_ds_formula(self):
        """c_{W_3}(k) = 2 - 24(k+2)^2/(k+3).

        From DS reduction of V_k(sl_3).
        """
        from lib.examples.w3_algebra import w3_central_charge
        k = Symbol('k')
        result = w3_central_charge(k)
        expected = 2 - 24 * (k + 2)**2 / (k + 3)
        assert simplify(result - expected) == 0

    def test_complementarity_sum(self):
        """c(k) + c(-k-6) = 100.

        The dual level for W_3 is k' = -k - 2h^v = -k - 6 (h^v = 3 for sl_3).
        The complementarity sum is 2*rank + 4*h^v*dim = 2*2 + 4*3*8 = 100.
        """
        from lib.examples.w3_algebra import w3_complementarity
        result = w3_complementarity()
        assert simplify(result - 100) == 0

    def test_ds_at_k1(self):
        """c_{W_3}(k=1) = 2 - 24*9/4 = 2 - 54 = -52."""
        from lib.examples.w3_algebra import w3_central_charge
        result = w3_central_charge(S.One)
        assert simplify(result - S(-52)) == 0

    def test_ds_at_k_minus3(self):
        """c_{W_3}(k=-3) is singular (critical level k = -h^v = -3).

        The DS central charge formula has a pole at k = -3 (denominator k+3 = 0).
        Use symbolic limit: as k -> -3, c(k) -> +-infinity.
        """
        from lib.examples.w3_algebra import w3_central_charge
        from sympy import zoo, oo, limit
        k = Symbol('k')
        c_k = w3_central_charge(k)
        # The limit from the right gives -infinity, from the left +infinity
        lim_right = limit(c_k, k, -3, '+')
        lim_left = limit(c_k, k, -3, '-')
        assert lim_right in (oo, -oo, zoo)
        assert lim_left in (oo, -oo, zoo)


# ===================================================================
# PRIMARITY AND CONFORMAL WEIGHTS
# ===================================================================

class TestW3ConformalStructure:
    """Verify conformal weight assignments and primarity."""

    def test_W_is_primary(self):
        """W is T-primary of weight 3: {T_lam W} = dW + 3*lam*W."""
        from lib.examples.w3_algebra import verify_W_primary
        lam = Symbol('lambda')
        assert verify_W_primary(lam) == 0

    def test_conformal_weights(self):
        """Conformal weights: T=2, W=3, Lambda=4, dT=3, dW=4."""
        from lib.examples.w3_algebra import conformal_weights, T, W, Lambda, dT, dW
        weights = conformal_weights()
        assert weights[T] == 2
        assert weights[W] == 3
        assert weights[Lambda] == 4
        assert weights[dT] == 3
        assert weights[dW] == 4

    def test_derivative_raises_weight(self):
        """d raises conformal weight by 1: wt(d^k phi) = wt(phi) + k."""
        from lib.examples.w3_algebra import (
            conformal_weights, T, dT, d2T, d3T, W, dW
        )
        weights = conformal_weights()
        assert weights[dT] == weights[T] + 1
        assert weights[d2T] == weights[T] + 2
        assert weights[d3T] == weights[T] + 3
        assert weights[dW] == weights[W] + 1


# ===================================================================
# SPECIAL VALUES OF c
# ===================================================================

class TestW3SpecialValues:
    """Test W_3 at special values of the central charge."""

    def test_beta_squared_at_c2(self):
        """Lambda coefficient at c=2: 32/(22+10) = 1."""
        from lib.examples.w3_algebra import beta_sq, c
        val = beta_sq.subs(c, 2)
        assert simplify(val - 1) == 0

    def test_beta_squared_at_c100(self):
        """Lambda coefficient at c=100: 32/(22+500) = 16/261."""
        from lib.examples.w3_algebra import beta_sq, c
        val = beta_sq.subs(c, 100)
        assert simplify(val - Rational(16, 261)) == 0

    def test_kappa_at_c_equals_2(self):
        """kappa(W_3) at c=2: 5*2/6 = 5/3."""
        from lib.examples.w3_algebra import w3_shadow_data, c
        data = w3_shadow_data()
        kappa_val = data['kappa'].subs(c, 2)
        assert simplify(kappa_val - Rational(5, 3)) == 0

    def test_complementarity_kappa_sum(self):
        """kappa(W_3, c) + kappa(W_3, 100-c) = 250/3.

        From complementarity: c + c' = 100, so
        kappa + kappa' = 5c/6 + 5(100-c)/6 = 500/6 = 250/3.

        Cross-reference: Vol I curvature_genus_bridge.py.
        """
        from lib.examples.w3_algebra import w3_shadow_data, c
        data = w3_shadow_data()
        kappa_c = data['kappa']
        kappa_dual = kappa_c.subs(c, 100 - c)
        assert simplify(kappa_c + kappa_dual - Rational(250, 3)) == 0

    def test_degenerate_c_minus_22_over_5(self):
        """At c = -22/5, the nonlinear coefficient has a pole.

        The W_3 algebra degenerates: the composite Lambda decouples
        in a singular way. This is a GENUINE singularity, not removable
        at the algebra level (though the Jacobi constraint is removable).
        """
        from lib.examples.w3_algebra import beta_sq, c
        from sympy import zoo
        val = beta_sq.subs(c, Rational(-22, 5))
        # Should be zoo (complex infinity) or equivalent
        assert val == zoo or val.is_infinite


# ===================================================================
# TRANSLATION OPERATOR
# ===================================================================

class TestW3TranslationOperator:
    """Verify the translation operator d acts correctly."""

    def test_partial_T(self):
        """d(T) = dT."""
        from lib.examples.w3_algebra import apply_partial, T, dT
        assert apply_partial(T) == dT

    def test_partial_dT(self):
        """d(dT) = d2T."""
        from lib.examples.w3_algebra import apply_partial, dT, d2T
        assert apply_partial(dT) == d2T

    def test_partial_W(self):
        """d(W) = dW."""
        from lib.examples.w3_algebra import apply_partial, W, dW
        assert apply_partial(W) == dW

    def test_partial_Lambda(self):
        """d(Lambda) = dLambda."""
        from lib.examples.w3_algebra import apply_partial, Lambda, dLambda
        assert apply_partial(Lambda) == dLambda

    def test_partial_constant(self):
        """d(c) = 0 (translation kills constants)."""
        from lib.examples.w3_algebra import apply_partial, c
        assert apply_partial(c) == 0

    def test_partial_leibniz(self):
        """d(T*W) = dT*W + T*dW (Leibniz rule)."""
        from lib.examples.w3_algebra import apply_partial, T, W, dT, dW
        result = apply_partial(T * W)
        expected = dT * W + T * dW
        assert simplify(result - expected) == 0


# ===================================================================
# CROSS-VOLUME CONSISTENCY
# ===================================================================

class TestW3CrossVolume:
    """Verify consistency with Vol I computations."""

    def test_nth_products_match_vol1(self):
        """n-th products match Vol I w3_bar.py ground truth.

        Vol I (comp:w3-nthproducts):
          W_{(5)}W = c/3, W_{(3)}W = 2T, W_{(2)}W = dT,
          W_{(1)}W = (3/10)d^2T + beta_Lambda*Lambda,
          W_{(0)}W = (1/15)d^3T + beta_partial_Lambda*dLambda
        """
        from lib.examples.w3_algebra import w3_nth_product, c, T, dT, d2T, d3T
        from lib.examples.w3_algebra import Lambda, dLambda, beta_sq, beta_partial_Lambda

        assert simplify(w3_nth_product('W', 'W', 5) - c / 3) == 0
        assert simplify(w3_nth_product('W', 'W', 3) - 2 * T) == 0
        assert simplify(w3_nth_product('W', 'W', 2) - dT) == 0

        expected_1 = Rational(3, 10) * d2T + beta_sq * Lambda
        assert simplify(expand(w3_nth_product('W', 'W', 1) - expected_1)) == 0

        expected_0 = Rational(1, 15) * d3T + beta_partial_Lambda * dLambda
        assert simplify(expand(w3_nth_product('W', 'W', 0) - expected_0)) == 0

    def test_WT_asymmetry(self):
        """W_{(0)}T = 2*dW, NOT dW.

        This asymmetry with T_{(0)}W = dW is a consequence of
        skew-symmetry and the Borcherds formula. Vol I records this
        explicitly (comp:w3-nthproducts).
        """
        from lib.examples.w3_algebra import w3_nth_product, dW
        assert simplify(w3_nth_product('W', 'T', 0) - 2 * dW) == 0
        assert simplify(w3_nth_product('T', 'W', 0) - dW) == 0
