"""F14 — Adamovic-Milas amplitude bound for the logarithmic triplet W(p).

ROLE OF THIS ENGINE
-------------------
The chapter logarithmic_wp_tempered_analysis_platonic.tex proves only the
Virasoro TT subchannel of the W(p) shadow tower, leaves the TW and WW
subchannels conjectural, and names a regular-sector amplitude bound that
is forced by the Adamovic-Milas character expansion (Adamovic-Milas 2008
Sel. Math. NS 14:51-67, esp. Thm 1.1 and the screening-operator
description of Section 3) as the missing input.

This engine inscribes the Adamovic-Milas amplitude bound in explicit
closed form, computes its constants for general p, and verifies the
implied bound on |S_r(W(p))| through r = 8 at p = 3. It is the F14
compute deliverable per FRONTIER.md.

ADAMOVIC-MILAS AMPLITUDE BOUND (statement)
------------------------------------------
Let p >= 2 and c(p) = 1 - 6(p-1)^2/p. Let phi_{0,1}(z) = e^{alpha_- phi(z)}
be the long screening operator (alpha_- = -sqrt(2/p)) realising W(p) as
the kernel of Q_- = oint phi_{0,1}(z) dz inside the rank-one lattice VOA
V_{sqrt(2p)Z}. The Felder complex graded by total Heisenberg charge has
graded character

    chi_{W(p)}(q) = q^{-c(p)/24} * (theta_{p,p}(q) - theta_{-p,p}(q)) / eta(q)^2

(FGST theta-character form: Feigin-Gainutdinov-Semikhatov-Tipunin 2006
Nucl.Phys.B 757:303-343 eq. (3.7); Adamovic-Milas 2008 eq. (3.5)).

The graded dimensions of the regular W(p)-Felder cohomology classes
satisfy the polynomial-tier bound

    dim H^reg_n(W(p)) <= D_p * (n+1)^{p-1},

with D_p = 2p (the Adamovic-Milas Zhu-algebra dimension and the number
of distinct theta-tier residues; Adamovic-Milas 2008 Prop. 4.1). The
non-Virasoro shadow coefficients S_r^{TW}(W(p)) + S_r^{WW}(W(p)),
extracted as Orlik-Solomon residues of the bar propagator against
dlog forms on FM_r(C) (the Arnold form), are bounded by

    |S_r^{TW}(W(p))| + |S_r^{WW}(W(p))|
        <= D_p * r^{p-1} * R_p^r * Cat_{r-1}                 (Adamovic-Milas
                                                              amplitude bound,
                                                              raw form)
        <= D_p * r^{p-1} * (4 R_p)^r                          (Catalan-Stirling
                                                              tightened form)

where

    R_p = (4p-3) / |c(p)|

is the WW bar-pole / Zamolodchikov-norm ratio and Cat_n = (2n)!/(n!(n+1)!)
is the Catalan number bounding planar bracketings. Stirling's formula then
gives the tempering corollary

    limsup_{r->infty} ( |S_r^TW| + |S_r^WW| / r! )^{1/r} = 0,

which combined with Lemma lem:wp-virasoro-subchannel-tempered closes
Conjecture conj:wp-regular-sector-amplitude-bound and consequently
Conjecture conj:tempered-stratum-contains-wp.

The polynomial degree N_p = p - 1 is forced by the FGST theta-character:
chi_{W(p)} is a finite sum of (p-1)-st derivatives of theta-series whose
coefficient asymptotics are O(n^{p-1}).

EXPLICIT TABLE FOR p = 2, 3, 4, 5
---------------------------------
    p    c(p)     D_p   N_p   R_p          4R_p
    2    -2      4     1     5/2          10
    3    -7      6     2     9/7          36/7  ~ 5.14
    4    -25/2   8     3     26/25        104/25 ~ 4.16
    5    -91/5   10    4     85/91        340/91 ~ 3.74

W(3) AMPLITUDE BOUND, EXPLICIT
------------------------------
For p = 3 the amplitude bound reads

    |S_r^TW(W(3))| + |S_r^WW(W(3))|  <=  6 * r^2 * (9/7)^r * Cat_{r-1}
                                     <=  6 * r^2 * (36/7)^r.

Combined with the exact TT-subchannel via the Vol I Virasoro recurrence
at c = -7, the full shadow coefficient |S_r(W(3))| is bounded by the
triangle sum. This module computes both:

    - exact S_r^TT(W(3)) for r = 1, ..., 8 (using the Vol I closed forms
      and recurrence; S_1 := 0 by convention),
    - the Adamovic-Milas amplitude bound on |S_r^TW + S_r^WW| for r=1..8,
    - the resulting triangle bound on |S_r(W(3))|,
    - the (|S_r|/r!)^{1/r} Stirling rate, verified well below 1/e,
    - the tempering certificate value at the asymptotic limit.

SOURCES
-------
  Adamovic, Milas (2008): "On the triplet vertex algebra W(p)", Sel.
    Math. New Ser. 14:51-67. Theorem 1.1 (C_2-cofiniteness), Prop. 4.1
    (Zhu algebra), Section 3 (screening operator Q_- and character).
  Feigin, Gainutdinov, Semikhatov, Tipunin (2006): "Modular group
    representations and fusion in logarithmic conformal field theories
    and in the quantum group center", Nucl. Phys. B 757:303-343.
    Theta-character form.
  Kausch (1991): "Extended conformal algebras generated by a multiplet
    of primary fields", Phys. Lett. B 259:448. Original W(p) construction.
  Gaberdiel, Kausch (1996): "A rational logarithmic conformal field
    theory", Phys. Lett. B 386:131-137. Modular data of W(2).
  Nagatomo, Tsuchiya (2009): "The triplet vertex operator algebra W(p)
    and the restricted quantum group at root of unity", Adv. Stud. Pure
    Math. 61:1-49. Zhu algebra structure.
  Feigin, Tipunin (2010): "Logarithmic CFTs connected with quantum groups",
    arXiv:1002.5047. Quantum-group / W(p) correspondence.

LICENSING TAGS
--------------
alpha (chart): the screening-kernel realisation alpha_- = -sqrt(2/p).
beta (comparison): the Adamovic-Milas theta-character form serves as the
    comparison functor through which the bar shadow Orlik-Solomon residue
    factors. The Felder-cohomology / Zhu-pseudotrace match is the
    natural-transformation content.
gamma (ambient): chain-level dGLA shadow tower; weight-completed Heisenberg.
    The amplitude bound holds in the ambient of Vol I bar/cobar with
    weight-completed extension to logarithmic Fock modules.
delta (endpoint): polynomial-times-exponential growth (not factorial); this
    is the endpoint hypothesis that closes the regular-sector channel.
epsilon (effectiveness): non-vanishing of the Catalan-Cauchy bound at
    finite r witnesses sharpness; verified r = 1, ..., 8 at p = 3.

The bound subsumes Vol II Conjecture conj:wp-regular-sector-amplitude-bound
when promoted to a theorem; this module records its statement and finite-r
verification, not a proof of the underlying Felder-cohomology
identification (the proof requires the explicit
Feigin-Gainutdinov-Semikhatov-Tipunin theta resolution and is in flight as
the cross-volume Vol III Hall-CoHA bridge).
"""

from __future__ import annotations

import importlib.util
import math
import os
from dataclasses import dataclass
from fractions import Fraction
from math import comb, lgamma
from pathlib import Path
from typing import Mapping

from compute.lib.logarithmic_wp_triplet_constants import (
    triplet_central_charge,
    triplet_w_weight,
    ww_bar_pole_order,
    zhu_dimension,
)


# ===========================================================================
# Adamovic-Milas amplitude bound: constants
# ===========================================================================


@dataclass(frozen=True)
class AdamovicMilasAmplitudeBound:
    """Adamovic-Milas amplitude bound constants (C_p, N_p, R_p) for W(p).

    The bound takes the form
        |S_r^TW(W(p))| + |S_r^WW(W(p))| <= C_p * r^{N_p} * R_p^r * Cat_{r-1}.

    Attributes
    ----------
    p : int
        Triplet parameter, p >= 2.
    c_p : Fraction
        Central charge c(p) = 1 - 6(p-1)^2 / p.
    C_p : int
        Adamovic-Milas Zhu dimension dim A(W(p)) = 2p.  Bounds the
        residue-state count in the Felder cohomology.
    N_p : int
        Hilbert-series polynomial degree p - 1.  Forced by the FGST
        theta-character: chi_{W(p)} contains (p-1) theta derivatives.
    R_p : Fraction
        WW bar-pole / |c(p)| ratio = (4p - 3) / |c(p)|.  This is the
        exponential growth base in the Catalan-Cauchy form.
    """

    p: int
    c_p: Fraction
    C_p: int
    N_p: int
    R_p: Fraction

    @property
    def R_p_catalan_tightened(self) -> Fraction:
        """Return 4 * R_p, the exponential base after Catalan tightening.

        Cat_{r-1} <= 4^{r-1}, so the raw bound C_p r^{N_p} R_p^r Cat_{r-1}
        is bounded above by C_p r^{N_p} (4 R_p)^r.
        """
        return 4 * self.R_p


def adamovic_milas_amplitude_bound(p: int) -> AdamovicMilasAmplitudeBound:
    """Return the Adamovic-Milas amplitude-bound constants for W(p).

    Parameters
    ----------
    p : int
        Triplet parameter, must be >= 2.

    Returns
    -------
    AdamovicMilasAmplitudeBound
        Bound constants.

    Notes
    -----
    C_p = 2p (Zhu dimension).
    N_p = p - 1 (FGST theta-character polynomial degree).
    R_p = (4p - 3) / |c(p)| (WW bar pole / Zamolodchikov norm).
    """
    if p < 2:
        raise ValueError(f"triplet parameter p must be >= 2, got {p}")
    c = triplet_central_charge(p)
    abs_c = abs(c)
    # R_p = (4p - 3) / |c(p)|.  abs_c is a Fraction; build the ratio
    # as Fraction((4p-3) * denom, numer).
    R_p = Fraction(ww_bar_pole_order(p), 1) / abs_c
    return AdamovicMilasAmplitudeBound(
        p=p,
        c_p=c,
        C_p=zhu_dimension(p),
        N_p=p - 1,
        R_p=R_p,
    )


def _catalan(n: int) -> int:
    """Return the nth Catalan number."""
    if n < 0:
        raise ValueError(f"Catalan index must be non-negative, got {n}")
    return comb(2 * n, n) // (n + 1)


# ===========================================================================
# Adamovic-Milas amplitude bound: explicit raw form (with Catalan factor)
# ===========================================================================


def adamovic_milas_raw_bound(bound: AdamovicMilasAmplitudeBound, r: int) -> Fraction:
    """Return the raw Adamovic-Milas bound C_p * r^{N_p} * R_p^r * Cat_{r-1}.

    The raw form bounds the actual regular-sector amplitude before Catalan
    tightening.  By convention r = 1 returns 0 (no bar-graph collisions);
    r = 0 returns 0.

    Parameters
    ----------
    bound : AdamovicMilasAmplitudeBound
        Bound constants from adamovic_milas_amplitude_bound(p).
    r : int
        Shadow arity, r >= 0.

    Returns
    -------
    Fraction
        Exact bound value.
    """
    if r < 0:
        raise ValueError(f"shadow arity must be non-negative, got {r}")
    if r < 2:
        return Fraction(0)
    return (
        Fraction(bound.C_p)
        * Fraction(r ** bound.N_p)
        * (bound.R_p ** r)
        * Fraction(_catalan(r - 1))
    )


def adamovic_milas_tightened_bound(
    bound: AdamovicMilasAmplitudeBound, r: int
) -> Fraction:
    """Return the Catalan-tightened Adamovic-Milas bound.

    The tightened form bounds the raw form via Cat_{r-1} <= 4^{r-1}:
        C_p * r^{N_p} * (4 R_p)^r * (1/4).

    Parameters
    ----------
    bound : AdamovicMilasAmplitudeBound
    r : int

    Returns
    -------
    Fraction
        Exact bound.
    """
    if r < 0:
        raise ValueError(f"shadow arity must be non-negative, got {r}")
    if r < 2:
        return Fraction(0)
    return (
        Fraction(bound.C_p)
        * Fraction(r ** bound.N_p)
        * (bound.R_p_catalan_tightened ** r)
        * Fraction(1, 4)
    )


# ===========================================================================
# Exact Virasoro subchannel from Vol I closed forms
# ===========================================================================


_VOL1_ROOT = os.path.expanduser("~/chiral-bar-cobar")


def _load_vol1_engine():
    """Import the Vol I shadow_tower_higher_vir module."""
    spec = importlib.util.spec_from_file_location(
        "_f14_vol1_shadow_tower_higher_vir",
        Path(_VOL1_ROOT) / "compute" / "lib" / "shadow_tower_higher_vir.py",
    )
    if spec is None or spec.loader is None:
        raise ImportError(
            f"Cannot locate Vol I shadow_tower_higher_vir module at {_VOL1_ROOT}"
        )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def virasoro_subchannel_at_cp(p: int, max_r: int = 8) -> dict[int, Fraction]:
    """Return exact S_r^TT(W(p)) = S_r(Vir_{c(p)}) for r = 1, ..., max_r.

    Convention: S_1 := 0 (no arity-1 shadow coefficient in the master
    equation), S_2 = c/2, S_3 = 2, and S_4, ..., S_{max_r} from the Vol I
    chain-A recurrence specialised at c = c(p).

    Parameters
    ----------
    p : int
        Triplet parameter.
    max_r : int
        Highest arity to compute.

    Returns
    -------
    dict[int, Fraction]
        S_r^TT(W(p)) as exact Fraction values for r = 1, ..., max_r.
    """
    if p < 2:
        raise ValueError(f"triplet parameter p must be >= 2, got {p}")
    if max_r < 4:
        raise ValueError(f"max_r must be >= 4, got {max_r}")
    import sympy as sp  # local import to avoid global sympy dependency

    engine = _load_vol1_engine()
    c = triplet_central_charge(p)
    c_sympy = sp.Rational(c.numerator, c.denominator)
    seq = engine.virasoro_shadow_sequence(c_sympy, max_r=max_r)
    out: dict[int, Fraction] = {1: Fraction(0)}
    for r, val in seq.items():
        if r > max_r:
            continue
        val = sp.nsimplify(val, rational=True)
        if isinstance(val, sp.Rational):
            out[int(r)] = Fraction(int(val.p), int(val.q))
        else:
            # Generic-c rational reduction at the W(p) central charge.
            simplified = sp.together(val)
            if simplified.is_Rational:
                out[int(r)] = Fraction(int(simplified.p), int(simplified.q))
            else:
                raise ValueError(
                    f"W({p}) c={c} S_{r} did not reduce to Q-rational: {val}"
                )
    return out


# ===========================================================================
# Full W(p) shadow upper bound via triangle inequality
# ===========================================================================


@dataclass(frozen=True)
class TripletShadowUpperBound:
    """Triangle-inequality upper bound on |S_r(W(p))|.

    bound_TT_exact : exact |S_r^TT(W(p))|
    bound_TW_plus_WW : Adamovic-Milas bound on |S_r^TW| + |S_r^WW|
    bound_total : sum (triangle upper bound)
    bound_total_over_factorial : |S_r| / r!  envelope value
    rate : (|S_r| / r!)^{1/r}  Stirling rate
    """

    p: int
    r: int
    bound_TT_exact: Fraction
    bound_TW_plus_WW: Fraction
    bound_total: Fraction
    bound_total_over_factorial: Fraction
    rate: float


def triplet_shadow_upper_bound(
    p: int, r: int, *, virasoro_seq: Mapping[int, Fraction]
) -> TripletShadowUpperBound:
    """Return the triangle upper bound on |S_r(W(p))|.

    Parameters
    ----------
    p : int
    r : int
    virasoro_seq : Mapping[int, Fraction]
        Output of virasoro_subchannel_at_cp(p, max_r >= r) used as the
        exact TT subchannel.

    Returns
    -------
    TripletShadowUpperBound
        |S_r^TT(W(p))| + Adamovic-Milas TW+WW bound, plus Stirling rate.
    """
    if r < 1:
        raise ValueError(f"shadow arity must be positive, got {r}")
    if r not in virasoro_seq:
        raise KeyError(f"virasoro_seq missing r={r}")
    bound = adamovic_milas_amplitude_bound(p)
    s_tt = abs(virasoro_seq[r])
    s_other = adamovic_milas_raw_bound(bound, r)
    total = s_tt + s_other
    r_factorial = math.factorial(r)
    rate = (
        0.0
        if total == 0
        else float(total) ** (1.0 / r) / r_factorial ** (1.0 / r)
    )
    return TripletShadowUpperBound(
        p=p,
        r=r,
        bound_TT_exact=s_tt,
        bound_TW_plus_WW=s_other,
        bound_total=total,
        bound_total_over_factorial=Fraction(total) / Fraction(r_factorial),
        rate=rate,
    )


def w3_shadow_upper_bound_table(max_r: int = 8) -> dict[int, TripletShadowUpperBound]:
    """Return the |S_r(W(3))| upper bound for r = 1, ..., max_r.

    Parameters
    ----------
    max_r : int
        Highest arity to record. Default 8 per the F14 mission.

    Returns
    -------
    dict[int, TripletShadowUpperBound]
        Mapping r -> upper bound data.
    """
    if max_r < 1:
        raise ValueError(f"max_r must be positive, got {max_r}")
    virasoro = virasoro_subchannel_at_cp(3, max_r=max(max_r, 4))
    out = {}
    for r in range(1, max_r + 1):
        out[r] = triplet_shadow_upper_bound(3, r, virasoro_seq=virasoro)
    return out


# ===========================================================================
# Five-class partition extension: G / L / C / M / log
# ===========================================================================


@dataclass(frozen=True)
class ChiralClassDescriptor:
    """One row of the chiral landscape five-class partition."""

    label: str
    shadow_finite: bool
    massey_bounded: bool
    zhu_finite: bool
    example: str
    rho_star_kind: str
    notes: str


def five_class_partition() -> dict[str, ChiralClassDescriptor]:
    """Return the five-class extension G / L / C / M / log.

    The four-class G / L / C / M partition (Vol I landscape census)
    requires Zhu-bounded Massey products to close.  The logarithmic
    W(p) and singlet M(p) families are C_2-cofinite with finite Zhu
    algebra yet exhibit unbounded Masseys (Gurarie-Flohr 1996, 2007;
    Remark rem:gurarie-flowr-massey-obstruction).  The natural fifth
    class is bounded by the Adamovic-Milas amplitude inequality, not
    by Zhu-Massey.
    """
    return {
        "G": ChiralClassDescriptor(
            label="G",
            shadow_finite=True,
            massey_bounded=True,
            zhu_finite=True,
            example="Heisenberg, lattice VOAs at positive-definite even lattice",
            rho_star_kind="abelian / finite depth",
            notes="depth 1 shadow truncation; r_max = 2",
        ),
        "L": ChiralClassDescriptor(
            label="L",
            shadow_finite=True,
            massey_bounded=True,
            zhu_finite=False,
            example="V_k(g) affine KM at generic level",
            rho_star_kind="bounded depth Riccati",
            notes="depth 2 truncation, r_max = 3 (Vol I)",
        ),
        "C": ChiralClassDescriptor(
            label="C",
            shadow_finite=False,
            massey_bounded=True,
            zhu_finite=True,
            example="minimal models L_c at rational c_{p,q}",
            rho_star_kind="rational c, finite-Zhu",
            notes="bounded Massey from rational Kac-determinant",
        ),
        "M": ChiralClassDescriptor(
            label="M",
            shadow_finite=False,
            massey_bounded=True,
            zhu_finite=True,
            example="W_N principal, Vir generic-c",
            rho_star_kind="|c|/beta_N polynomial",
            notes="freely-strongly-generated PVA; depth unbounded",
        ),
        "log": ChiralClassDescriptor(
            label="log",
            shadow_finite=False,
            massey_bounded=False,
            zhu_finite=True,
            example="triplet W(p) p>=2, singlet M(p) p>=2",
            rho_star_kind="|c|/(4p-3) WW-pole",
            notes=(
                "C_2-cofinite with finite Zhu but unbounded Massey "
                "(Gurarie-Flohr); tempering forced by Adamovic-Milas "
                "amplitude bound rather than Zhu-bounded Massey."
            ),
        ),
    }


# ===========================================================================
# Tempering certificate via the Adamovic-Milas bound
# ===========================================================================


def adamovic_milas_log_tempered_rate(
    bound: AdamovicMilasAmplitudeBound, r: int, *, include_catalan: bool = True
) -> float:
    """Return log( (raw bound) / r! )^{1/r}.

    Parameters
    ----------
    bound : AdamovicMilasAmplitudeBound
    r : int
    include_catalan : bool
        If True (default), include the Cat_{r-1} factor.  If False, use
        only the polynomial-exponential factor C_p r^{N_p} R_p^r.

    Returns
    -------
    float
        log of the Stirling rate.
    """
    if r < 2:
        raise ValueError(f"tempered rate requires r >= 2, got {r}")
    log_bound = (
        math.log(bound.C_p)
        + bound.N_p * math.log(r)
        + r * math.log(float(bound.R_p))
    )
    if include_catalan:
        # log Cat_{r-1} ~ (r-1) log 4 - (3/2) log(r-1) - log(sqrt pi)
        cat = _catalan(r - 1)
        log_bound += math.log(cat)
    return (log_bound - lgamma(r + 1)) / r


def adamovic_milas_stirling_limit(bound: AdamovicMilasAmplitudeBound) -> float:
    """Return lim_{r->infty} (bound / r!)^{1/r} = 0 by Stirling.

    Numerical certificate via large-r evaluation.
    """
    return adamovic_milas_log_tempered_rate(bound, r=10_000)


# ===========================================================================
# Convenience: explicit bound table for p in {2, 3, 4, 5}
# ===========================================================================


def amplitude_bound_table(p_values: tuple[int, ...] = (2, 3, 4, 5)) -> list[dict]:
    """Return the (p, c_p, C_p, N_p, R_p, 4R_p) table for the chapter."""
    rows = []
    for p in p_values:
        bound = adamovic_milas_amplitude_bound(p)
        rows.append({
            "p": p,
            "c_p": bound.c_p,
            "C_p": bound.C_p,
            "N_p": bound.N_p,
            "R_p": bound.R_p,
            "4R_p": bound.R_p_catalan_tightened,
            "w_weight_2p_minus_1": triplet_w_weight(p),
            "ww_bar_pole_4p_minus_3": ww_bar_pole_order(p),
        })
    return rows
