#!/bin/bash
exit 0

INPUT=$(cat)
CMD=$(printf '%s' "$INPUT" | jq -r '.tool_input.command // ""')
CMD_LC=$(printf '%s' "$CMD" | tr '[:upper:]' '[:lower:]')

deny() {
  local reason="$1"
  jq -n --arg reason "$reason" '{
    "hookSpecificOutput": {
      "hookEventName": "PreToolUse",
      "permissionDecision": "deny",
      "permissionDecisionReason": $reason
    }
  }'
  exit 0
}

if [[ "$CMD_LC" =~ git[[:space:]]+reset[[:space:]]+--hard ]]; then
  deny "Destructive command blocked: use surgical inspection and targeted edits instead of git reset --hard."
fi

if [[ "$CMD_LC" =~ git[[:space:]]+checkout[[:space:]]+-- ]]; then
  deny "Destructive command blocked: do not discard worktree changes with git checkout --."
fi

if [[ "$CMD_LC" =~ git[[:space:]]+clean[[:space:]]+-f ]]; then
  deny "Destructive command blocked: git clean requires explicit human intent."
fi

if [[ "$CMD_LC" =~ (^|[[:space:]])rm[[:space:]]+-rf[[:space:]]+(/|~|\.($|[[:space:]])) ]]; then
  deny "Destructive command blocked: broad rm -rf targets are forbidden in this repo."
fi

if [[ "$CMD_LC" =~ git[[:space:]]+commit ]]; then
  if git diff --cached 2>/dev/null | grep -Eiq 'co-authored-by:|generated by|written with chatgpt|written with claude|ai-assisted|ai generated|created by chatgpt|created by claude|llm-assisted'; then
    deny "Commit blocked: staged content appears to contain AI attribution, which is forbidden in this repo."
  fi

  jq -n '{
    "systemMessage": "Pre-commit gate: verify the narrowest relevant build/tests, and ensure neither staged content nor the commit message contains any AI attribution."
  }'
fi
