"""
Free chiral multiplet: the simplest A-infinity chiral algebra.

BV fields: phi (scalar, degree 0), psi (antifield, degree 1)
Action: S = integral psi (d_t + dbar) phi on C x R
Propagator: K(t,z) = Theta(t) / (2pi z)

The BV-BRST differential is:
    Q(phi_n) = psi_n,   Q(psi_n) = 0.

Note that Q^2 = 0: Q^2(phi_n) = Q(psi_n) = 0.

Key claims to verify:
- m_1 = Q with Q(phi) = psi, Q(psi) = 0, and Q^2 = 0
- m_2(phi, psi; lambda) encodes the phi-psi propagator
- m_{k>=3} = 0 (no interaction vertices -> no higher operations)
- H*(A,Q) = C (trivial, since each (phi_n, psi_n) is an acyclic doublet)
- (H1)-(H4) are trivially satisfied

Paper reference: Section 11 (examples-computing.tex), first example.
"""
from sympy import Symbol, S as Sym


def m1(field, field_type):
    """BV-BRST differential Q.

    Q(phi_n) = psi_n,  Q(psi_n) = 0.

    This satisfies Q^2 = 0:
        Q^2(phi_n) = Q(psi_n) = 0.

    Parameters:
        field: the field value (symbolic)
        field_type: 'phi' or 'psi'

    Returns:
        Q(field): psi_n if field_type='phi', 0 if field_type='psi'
    """
    if field_type == 'phi':
        return field  # Q(phi_n) = psi_n (identified by index)
    elif field_type == 'psi':
        return Sym.Zero  # Q(psi_n) = 0
    else:
        raise ValueError(f"Unknown field type: {field_type}")


def check_Q_squared(field, field_type):
    """Verify Q^2 = 0.

    Q^2(phi_n) = Q(Q(phi_n)) = Q(psi_n) = 0.  ✓
    Q^2(psi_n) = Q(0) = 0.  ✓
    """
    Qf = m1(field, field_type)
    if field_type == 'phi':
        Q2f = m1(Qf, 'psi')  # Q(psi_n) = 0
    else:
        Q2f = Sym.Zero
    assert Q2f == Sym.Zero, f"Q^2 != 0 on {field_type}: got {Q2f}"
    return Sym.Zero


def m2(a, b, lam=None):
    """Binary operation: the phi-psi propagator.

    For free theory, m_2(phi, psi; lambda) encodes the propagator
    <phi(z_1) psi(z_2)> = 1/(z_1 - z_2).

    The lambda-bracket is {phi_lambda psi} = 1.
    On cohomology (which is just C), the bracket is trivial.
    """
    return a * b


def m_k(k, *args):
    """Higher operations: all zero for k >= 3.

    Reason: Free theory has no interaction vertices, so all Feynman
    diagrams with k >= 3 inputs vanish. This is the defining feature
    of a "free" A-infinity chiral algebra.
    """
    if k <= 0:
        raise ValueError(f"Arity must be positive, got {k}")
    if k == 1:
        # Note: caller must also specify field_type for m1
        raise ValueError("Use m1() directly for the differential")
    if k == 2:
        return m2(args[0], args[1])
    return Sym.Zero


def product_on_cohomology(a, b):
    """Commutative product on H*(A,Q) = C.

    Since cohomology is one-dimensional (generated by 1),
    the product is just multiplication of scalars.
    """
    return a * b


def lambda_bracket(a, b, lam):
    """Lambda-bracket on H*(A,Q) = C.

    For free theory, the descended lambda-bracket on cohomology
    is identically zero (the cohomology is one-dimensional).
    """
    return Sym.Zero
