"""
Virasoro algebra as an A-infinity chiral algebra.

The stress tensor T of the bc ghost system (or any c-number Virasoro)
satisfies the OPE:
  T(z)T(w) ~ (c/2)/(z-w)^4 + 2T(w)/(z-w)^2 + partial T(w)/(z-w)

Equivalently, the lambda-bracket:
  {T_lambda T} = partial T + 2T lambda + (c/12) lambda^3

Key claims to verify:
- This lambda-bracket satisfies PVA skew-symmetry
- This lambda-bracket satisfies Jacobi identity
- The coefficient c/12 (not c/2) in the lambda-bracket vs c/2 in OPE
- No truncation: the A-infinity structure is genuinely infinite (m_k != 0 for all k >= 3)

Paper references: Section 20 (w-algebras.tex).

CRITICAL CHECK: The lambda-bracket coefficient is c/12 because
the OPE has c/2 at fourth order pole, and the lambda-bracket
packages this as (c/2) * lambda^3 / 3! = (c/12) * lambda^3.
"""
from sympy import Symbol, Rational, expand, simplify, S, Function, symbols, Poly


# ---------------------------------------------------------------------------
# Generators and translation operator
# ---------------------------------------------------------------------------
# We work in the polynomial PVA generated by T.
# ∂^k T are represented as distinct symbols: T, dT, d2T, d3T, ...
# The translation operator ∂ acts by:  ∂(∂^k T) = ∂^{k+1} T.
# On constants (including spectral parameters): ∂(c) = 0.

T = Symbol('T')
dT = Symbol('dT')       # ∂T
d2T = Symbol('d2T')     # ∂²T
d3T = Symbol('d3T')     # ∂³T


def _apply_partial(expr):
    """Apply the translation operator ∂ to an expression in T, dT, d2T, ...

    ∂ acts as a derivation:
      ∂(T) = dT, ∂(dT) = d2T, ∂(d2T) = d3T
      ∂(const) = 0  (including spectral parameters λ, μ, c)
      ∂(f·g) = ∂(f)·g + f·∂(g)
    """
    # Use sympy's diff with a dummy variable to implement the derivation.
    # Map T -> t, dT -> t', etc., differentiate, map back.
    # Simpler: use the substitution rules directly.
    return (expr.diff(T) * dT +
            expr.diff(dT) * d2T +
            expr.diff(d2T) * d3T)


def virasoro_lambda_bracket(a, b, lam, partial, c):
    """Compute {a_lambda b} for the Virasoro PVA.

    For generators T:
      {T_lambda T} = partial(T) + 2*T*lambda + (c/12)*lambda^3

    Parameters:
        a, b: should be the symbol T (or expressions in T)
        lam: spectral parameter lambda
        partial: translation operator (acts as derivative) — UNUSED,
                 kept for API compatibility. Use _apply_partial instead.
        c: central charge
    """
    if a == T and b == T:
        return dT + 2 * T * lam + Rational(1, 12) * c * lam**3

    return S.Zero


def _bracket_TT(lam, c):
    """Core Virasoro λ-bracket: {T_λ T}."""
    return dT + 2 * T * lam + Rational(1, 12) * c * lam**3


def _bracket_sesqui_right(lam, c):
    """Compute {T_λ ∂T} = (λ + ∂){T_λ T}.

    Right sesquilinearity: {a_λ ∂b} = (λ + ∂){a_λ b}.

    (λ + ∂)(∂T + 2Tλ + (c/12)λ³)
    = λ·∂T + 2Tλ² + (c/12)λ⁴ + ∂²T + 2(∂T)λ + 0
    = ∂²T + 3(∂T)λ + 2Tλ² + (c/12)λ⁴
    """
    bracket = _bracket_TT(lam, c)
    return expand(lam * bracket + _apply_partial(bracket))


def _bracket_sesqui_left(nu, c):
    """Compute {∂T_ν T} = −ν · {T_ν T}.

    Left sesquilinearity: {∂a_ν b} = −ν · {a_ν b}.
    """
    return expand(-nu * _bracket_TT(nu, c))


def check_virasoro_skew_symmetry(lam, partial, c):
    """Verify {T_lambda T} = -{T_{-lambda-partial} T}.

    Uses the Borcherds formula with n-products.

    The n-products from the OPE T(z)T(w) are:
      T_0 T = partial T
      T_1 T = 2T
      T_2 T = 0
      T_3 T = c/2

    RHS via Borcherds: -sum_n (-partial-lambda)^n/n! * (T_n T)
    For the Virasoro:
      n=0: -1 * dT = -dT
      n=1: -(-lambda) * 2T = 2T*lambda  (∂ acts on the RESULT 2T, giving 2dT)
            Full: -(−λ−∂)/1! * 2T = (λ+∂)(2T) = 2Tλ + 2dT
      n=3: -(−λ−∂)³/3! * (c/2)
            On the constant c/2: ∂^k(c/2) = 0 for k≥1
            So (−λ−∂)³(c/2) = (−λ)³·(c/2) = −λ³c/2
            -(−λ³c/2)/6 = λ³c/12

    Total RHS = -dT + 2Tλ + 2dT + (c/12)λ³ = dT + 2Tλ + (c/12)λ³ = LHS ✓
    """
    lhs = _bracket_TT(lam, c)

    # Borcherds formula computation
    rhs_n0 = -dT  # -1 * (T_0 T)
    rhs_n1 = expand(2 * T * lam + 2 * dT)  # (λ+∂)(2T)
    rhs_n3 = Rational(1, 12) * c * lam**3  # -(−λ)³/(3!)·(c/2)

    rhs = expand(rhs_n0 + rhs_n1 + rhs_n3)
    return simplify(expand(lhs - rhs))  # Should be 0


def check_virasoro_jacobi(lam, mu, c):
    """Verify Jacobi identity for Virasoro — REAL COMPUTATION.

    {T_λ {T_μ T}} − {T_μ {T_λ T}} = {{T_λ T}_{λ+μ} T}

    Method: Expand both sides using sesquilinearity rules and verify
    polynomial identity in T, dT, d2T, λ, μ.

    LHS computation:
      {T_λ {T_μ T}} = {T_λ (∂T + 2Tμ + (c/12)μ³)}
                     = {T_λ ∂T} + 2μ·{T_λ T}  [linearity, {T_λ const}=0]
      where {T_λ ∂T} = (λ+∂){T_λ T}  [right sesquilinearity]

    RHS computation:
      {T_λ T} = ∂T + 2Tλ + (c/12)λ³
      {{T_λ T}_{ν} T} with ν=λ+μ:
      = {∂T_ν T} + 2λ·{T_ν T} + (c/12)λ³·{1_ν T}
      = −ν·{T_ν T} + 2λ·{T_ν T}       [{∂a_ν b}=−ν{a_ν b}, {1_ν T}=0]
      = (2λ−ν)·{T_ν T}
      = (λ−μ)·{T_ν T}
    """
    nu = lam + mu

    # --- LHS Term 1: {T_λ {T_μ T}} ---
    # {T_λ ∂T} = (λ+∂){T_λ T}
    bracket_T_dT_lam = _bracket_sesqui_right(lam, c)
    # {T_λ T}
    bracket_TT_lam = _bracket_TT(lam, c)
    # {T_λ {T_μ T}} = {T_λ ∂T} + 2μ·{T_λ T}
    term1 = expand(bracket_T_dT_lam + 2 * mu * bracket_TT_lam)

    # --- LHS Term 2: {T_μ {T_λ T}} --- (swap λ ↔ μ)
    bracket_T_dT_mu = _bracket_sesqui_right(mu, c)
    bracket_TT_mu = _bracket_TT(mu, c)
    term2 = expand(bracket_T_dT_mu + 2 * lam * bracket_TT_mu)

    lhs = expand(term1 - term2)

    # --- RHS: {{T_λ T}_{λ+μ} T} = (λ−μ)·{T_{λ+μ} T} ---
    bracket_TT_nu = _bracket_TT(nu, c)
    rhs = expand((lam - mu) * bracket_TT_nu)

    result = expand(lhs - rhs)

    # Collect and simplify (result is polynomial in T, dT, d2T, λ, μ, c)
    return simplify(result)


def check_virasoro_jacobi_via_components(lam, mu, c):
    """Alternative Jacobi check: verify component by component.

    Both sides are polynomials in T, dT, d2T with coefficients in Z[λ,μ,c].
    Extract and compare each field-monomial coefficient independently.
    This is more robust than relying on simplify() for multivariate polynomials.
    """
    nu = lam + mu

    # LHS Term 1: {T_λ {T_μ T}} = {T_λ ∂T} + 2μ·{T_λ T}
    # {T_λ ∂T} = ∂²T + 3(∂T)λ + 2Tλ² + (c/12)λ⁴
    # {T_λ T} = ∂T + 2Tλ + (c/12)λ³
    t1 = expand(d2T + 3*dT*lam + 2*T*lam**2 + Rational(1, 12)*c*lam**4
                + 2*mu*(dT + 2*T*lam + Rational(1, 12)*c*lam**3))

    # LHS Term 2: {T_μ {T_λ T}} (swap λ↔μ in term1)
    t2 = expand(d2T + 3*dT*mu + 2*T*mu**2 + Rational(1, 12)*c*mu**4
                + 2*lam*(dT + 2*T*mu + Rational(1, 12)*c*mu**3))

    lhs = expand(t1 - t2)

    # RHS: (λ−μ)·{T_{λ+μ} T} = (λ−μ)·(∂T + 2T(λ+μ) + (c/12)(λ+μ)³)
    rhs = expand((lam - mu) * (dT + 2*T*nu + Rational(1, 12)*c*nu**3))

    diff = expand(lhs - rhs)

    # Extract coefficients of each field monomial
    results = {}
    for field, name in [(T, 'T'), (dT, 'dT'), (d2T, 'd2T')]:
        coeff_in_diff = diff.coeff(field)
        # Remove the field from the remaining terms
        results[name] = simplify(coeff_in_diff)

    # Also check the pure-constant part (no T, dT, d2T)
    const_part = diff.subs([(T, 0), (dT, 0), (d2T, 0), (d3T, 0)])
    results['const'] = simplify(const_part)

    return results


def ope_to_lambda_bracket_coefficient_check(c):
    """Verify the OPE -> lambda-bracket coefficient conversion.

    OPE: T(z)T(w) ~ (c/2)/(z-w)^4 + 2T(w)/(z-w)^2 + dT(w)/(z-w)

    n-products (from OPE): T_n T = Res_{z->w} (z-w)^n T(z)T(w)
      T_0 T = dT (coefficient of 1/(z-w))
      T_1 T = 2T (coefficient of 1/(z-w)^2)
      T_2 T = 0
      T_3 T = c/2 (coefficient of 1/(z-w)^4)

    Lambda-bracket: {T_lam T} = sum_{n>=0} (T_n T) * lam^n / n!
      = dT + 2T*lam + (c/12)*lam^3

    So the c/12 coefficient comes from c/2 divided by 3! = 6.
    """
    ope_fourth_pole = Rational(1, 2) * c  # c/2
    factorial_3 = 6
    lambda_bracket_coeff = ope_fourth_pole / factorial_3  # c/12

    expected = Rational(1, 12) * c
    return simplify(lambda_bracket_coeff - expected)  # Should be 0


def check_virasoro_leibniz(lam, c):
    """Verify the Leibniz rule for Virasoro PVA.

    For a PVA with product · and bracket {·_λ ·}:
      {a_λ b·c} = {a_λ b}·c + b·{a_λ c}

    For Virasoro with ONE generator T, the product is commutative:
      T·T is a new element (composite field :TT:).

    Since the Virasoro PVA is generated by T alone, the Leibniz rule
    is automatically satisfied on generators (there's only one generator,
    so a=b=c=T, and we need T·T which requires extending to composites).

    This check verifies the restricted Leibniz with ∂:
      {T_λ ∂T} = (λ+∂){T_λ T}  (which IS the right sesquilinearity, equivalent to Leibniz with ∂)
    """
    lhs = _bracket_sesqui_right(lam, c)  # {T_λ ∂T}
    bracket = _bracket_TT(lam, c)
    rhs = expand(lam * bracket + _apply_partial(bracket))  # (λ+∂){T_λ T}
    return simplify(expand(lhs - rhs))
